export default {
  login: "ronim",
  id: 6507041,
  node_id: "MDQ6VXNlcjY1MDcwNDE=",
  avatar_url: "https://avatars.githubusercontent.com/u/6507041?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/ronim",
  html_url: "https://github.com/ronim",
  followers_url: "https://api.github.com/users/ronim/followers",
  following_url: "https://api.github.com/users/ronim/following{/other_user}",
  gists_url: "https://api.github.com/users/ronim/gists{/gist_id}",
  starred_url: "https://api.github.com/users/ronim/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/ronim/subscriptions",
  organizations_url: "https://api.github.com/users/ronim/orgs",
  repos_url: "https://api.github.com/users/ronim/repos",
  events_url: "https://api.github.com/users/ronim/events{/privacy}",
  received_events_url: "https://api.github.com/users/ronim/received_events",
  type: "User",
  site_admin: false,
  name: "Ronim karki",
  company: "Top secret",
  blog: "",
  location: null,
  email: "ronim.karki@gmail.com",
  hireable: null,
  bio: "Hey i am a web developer, I like react js very much as it is easy to use",
  twitter_username: "Ronim.karki",
  public_repos: 0,
  public_gists: 0,
  followers: 1500,
  following: 0,
  created_at: "2014-01-26T14:51:41Z",
  updated_at: "2016-02-27T13:39:43Z",
}
